const mongoose =require('mongoose');
const firmSchema=new mongoose.Schema({
    firmName:{
        type:String,
        required:true
    },area:{
        type:String,
        required:true
    },category:{
        type:[
            {
                type:String,
                enum:["veg","non-veg"]
            }
        ],
        required:true
    },region:{
        type:[
            {
                type:String,
                enum:["south-indian","north-indian","chinese","Bakery"]
            }
        ]
    },offer:{
        type:String
    },image:{
        type:String
    },vendor:[
        {
            type: mongoose.Schema.Types.ObjectId,
            ref:'Vendor'
        }
    ],product:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'Product'
        }
    ]
})
module.exports=mongoose.model('Firm',firmSchema);